from fpdf import FPDF
from datetime import datetime
from flask import session

class MyPDF(FPDF):
    def header(self):
        self.set_font("Arial", style='I', size=8)
        self.cell(0, 0, txt="Generated on: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"), ln=False, align='L')
        self.cell(0, 0, txt="Generated by: " + session.get('name', "Unknown"), ln=True, align='R')
        self.ln(15)

    def footer(self):
        # Go to 1.5 cm from the bottom
        self.set_y(-15)
        
        # Set the font for the footer
        self.set_font('Arial', 'I', 8)
        
        # Page number in the format "Page x of y"
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')