"""set change int to nullable

Revision ID: 6f94b09ef839
Revises: f1208d207685
Create Date: 2025-04-24 02:32:00.488793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f94b09ef839'
down_revision = 'f1208d207685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_forecast', schema=None) as batch_op:
        batch_op.alter_column('change',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_forecast', schema=None) as batch_op:
        batch_op.alter_column('change',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
