"""created database

Revision ID: f1208d207685
Revises: 
Create Date: 2025-02-19 17:16:40.783827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1208d207685'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.String(length=10), nullable=False),
    sa.Column('bag_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_type_id'], ['bag_type.id'], name='fk_daily_forecast_bag_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_date', 'bag_type_id', name='uq_daily_forecast_date_bag_type')
    )
    op.create_table('daily_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.String(length=10), nullable=False),
    sa.Column('bag_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_type_id'], ['bag_type.id'], name='fk_daily_production_bag_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_date', 'bag_type_id', name='uq_daily_production_date_bag_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_production')
    op.drop_table('daily_forecast')
    op.drop_table('employee')
    op.drop_table('bag_type')
    # ### end Alembic commands ###
